name: rsync with SSH agent

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  rsync_with_ssh_agent:
    runs-on: ubuntu-22.04
    env:
      SSH_AUTH_SOCK: /tmp/agent.socket
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-client rsync
      - name: Save SSH id to file
        run: install -D -m 600 <(echo "${{ secrets.SSH_KEY }}") ~/.ssh/id
      - name: Start agent
        run: ssh-agent -a $SSH_AUTH_SOCK > /tmp/agent.env
      - name: Add identity
        run: echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id
      - name: List identities
        run:  ssh-add -l
      - name: Create ssh config
        run: |
          cat > ~/.ssh/config <<-Here
          StrictHostKeyChecking accept-new
          IdentityFile ~/.ssh/id
          IdentitiesOnly yes
          User ${{ secrets.SSH_USER }}
          Host remote
          Hostname ${{ secrets.SSH_HOST }}
          Here
      - name: Show config
        run: cat ~/.ssh/config
      - name: Test rsync
        run: rsync --exclude '.*' --recursive --delete-excluded --verbose . 'remote:/deploy/path\ with\ blank'
      - name: Kill agent
        run: |
          source /tmp/agent.env
          ssh-agent -k
