name: rsync with SSH agent (from action)

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  rsync_with_ssh_agent:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-client rsync
      - uses: mschmitt/rsync-with-ssh-agent@HEAD
        with: 
            SSH_KEY: ${{ secrets.SSH_KEY }}
            SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_PORT: ${{ secrets.SSH_PORT }}
            RSYNC_REMOTE_PATH: .
            RSYNC_LOCAL_PATH: .
            RSYNC_OPTIONS: ''
